site_name: UDIR Pipelines

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_portal_ref_pages.py
#  - literate-nav:
#      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ir-pipelines/ir-pell-accepts/src
            - ir-pipelines/ir-team-exercise/src
          options:
            show_source: false
            show_signature_annotations: true
            docstring_section_style: table

nav:
  - Home: index.md
  - Pipelines: SUMMARY.md
  - Software: software.md
  - Initial Steps: initialize.md
  - Running A Pipeline: run_pipeline.md
  