site_name: UDIR Pipelines

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - fenced_code
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_portal_ref_pages.py
#  - literate-nav:
#      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ir-pipelines/ir-pell-accepts/src
            - ir-pipelines/ir-team-exercise/src
            - ir-pipelines/ir-enrollment-projection/src
          options:
            show_source: false
            show_signature_annotations: true
            docstring_section_style: table

nav:
  - Home: index.md
  - Pipelines: SUMMARY.md
  - Software: software.md
  - Initialize Software: initialize.md
  - Run A Pipeline: run_pipeline.md
  - Add New Submodule: add_new_submodule.md
  - Update Submodules: update_submodules.md
  - Add New Documentation: add_new_documentation.md 
  - Python -> ODS: python_to_ods.md 
  - Create Git Repo: new_git_repo.md
  